### ISSUE TITLE
Use wp_remote_get instead of file_get_contents

### ISSUE THREAD

**Issue by dannyvankooten** [NikV/chuck-norris-plugin#1]
Hi Nikhil,

Most people have `file_get_contents` disabled for URL's (`allow_url_fopen` in their PHP configuration) for security reasons. A better idea would be to use `wp_remote_get` ([link](http://codex.wordpress.org/Function_Reference/wp_remote_get)).

It's real easy and actually tries various HTTP transport methods. :+1:

Keep up the good work!

**Comment by NikV** [comment]
Done, thanks for the recommendations!
